// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "base-url": string;
      "api-key": string;
      "model": string;
      "source-language": string;
      "target-language": string;
      "qps": number;
      "pool-max-workers": number;
      "watermark-output-mode": string;
      "translation-output-mode": string;
    };
  }
}
